# Generated by Django 2.1.1 on 2018-09-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='programa',
        ),
    ]
